// Generated by CoffeeScript 1.4.0
(function() {
  var files;

  files = require('../models/file');

  module.exports = function(app) {
    app.post('/files', function(req, res) {
      if (!req.user) {
        return res.redirect('/login');
      } else if (req.files.uploadFile) {
        return files.upload(req.user, req.files.uploadFile, function(err) {
          if (!err) {
            return res.redirect('/member');
          } else {
            return res.end('Error Saving File: ' + err);
          }
        });
      } else {
        return res.end("you didnt send me a file....");
      }
    });
    return app.get('/files/:id', function(req, res) {
      return files.read(req.params.id, function(err, fileData) {
        return console.log(fileData);
      });
    });
  };

}).call(this);
