// Generated by CoffeeScript 1.4.0
(function() {
  var User, files;

  files = require('../models/file');

  User = require('../models/user');

  module.exports = function(app) {
    app.post('/files', function(req, res) {
      if (!req.user) {
        return res.redirect('/login');
      } else if (req.files.uploadFile) {
        return files.upload(req.user, req.files.uploadFile, function(err) {
          if (!err) {
            return res.redirect('/account');
          } else {
            return res.end('Error Saving File: ' + err);
          }
        });
      } else {
        return res.end("you didnt send me a file....");
      }
    });
    app.get('/files/:username/:filename', function(req, res) {
      if (!req.user) {
        return res.redirect('/login');
      } else if (req.user.username === req.params.username) {
        return files.read(req.params.username, req.params.filename, function(err, fileData) {
          return res.end(fileData, "binary");
        });
      } else {
        return res.end("Dude, you don't have access to " + req.user.username + "'s files.");
      }
    });
    return app["delete"]('/files/:username/:filename', function(req, res) {
      if (!req.user) {
        return res.redirect('/login');
      } else if (req.user.username === req.params.username) {
        return files.remove(req.params.username, req.params.filename, function(err, result) {
          if (!err) {
            req.user.files.splice(req.user.files.indexOf(req.params.filename), 1);
            return req.user.save(function(err) {
              if (!err) {
                return res.redirect('/account');
              }
            });
          }
        });
      } else {
        return res.end("Dude, you don't have access to " + req.params.username + "'s files.");
      }
    });
  };

}).call(this);
