// Generated by CoffeeScript 1.4.0
(function() {
  var Chunk, GridStore, ObjectID, Server, db, mongodb;

  mongodb = require('mongodb');

  ObjectID = mongodb.ObjectID;

  GridStore = mongodb.GridStore;

  Chunk = mongodb.Chunk;

  Server = mongodb.Server;

  db = new mongodb.Db('nodejitsudb324588986231', new mongodb.Server('alex.mongohq.com', 10064), {
    safe: true
  });

  exports.setupFiles = function() {
    return db.open(function(err, db) {
      if (!err) {
        return db.authenticate('nodejitsu', '058361c64bc7258c3383439e270402a3', function(err, data) {
          if (err) {
            return console.log(err);
          } else {
            return console.log('database open');
          }
        });
      } else {
        return console.log(err);
      }
    });
  };

  exports.upload = function(user, file, cb) {
    var fileid, gs;
    fileid = new ObjectID();
    gs = new GridStore(db, fileid, 'w', {
      'content_type': file.type,
      'metadata': {
        author: user.username
      },
      'chunk_size': 1024 * 256
    });
    return gs.writeFile(file.path, function(err, gs) {
      if (!err) {
        user.files.push({
          fid: fileid,
          name: file.filename
        });
        return user.save(function(err, doc) {
          return cb(err);
        });
      } else {
        return cb(err);
      }
    });
  };

  exports.read = function(fid, cb) {
    var gs;
    gs = new GridStore(db, fid, 'r');
    return gs.read(cb);
  };

}).call(this);
