// Generated by CoffeeScript 1.4.0
(function() {
  var Chunk, GridStore, ObjectID, Server, db, mongodb;

  mongodb = require('mongodb');

  ObjectID = mongodb.ObjectID;

  GridStore = mongodb.GridStore;

  Chunk = mongodb.Chunk;

  Server = mongodb.Server;

  db = new mongodb.Db('nodejitsudb781130499355', new mongodb.Server('alex.mongohq.com', 10007), {
    safe: true
  });

  exports.setupFiles = function() {
    return db.open(function(err, db) {
      if (!err) {
        return db.authenticate('nodejitsu', 'e4f1505e6b587015b660a9b3d4a3364c', function(err, data) {
          if (err) {
            return console.log(err);
          } else {
            return console.log('database open');
          }
        });
      } else {
        return console.log(err);
      }
    });
  };

  exports.upload = function(user, file, cb) {
    var gs;
    gs = new GridStore(db, user.username + '/' + file.filename, 'w', {
      'content_type': file.type,
      'metadata': {
        author: user.username
      },
      'chunk_size': 1024 * 256
    });
    return gs.writeFile(file.path, function(err, gs) {
      if (!err) {
        if (user.files.indexOf(file.filename) === -1) {
          user.files.push(file.filename);
          return user.save(function(err, doc) {
            return cb(err);
          });
        } else {
          return cb(null);
        }
      } else {
        return cb(err);
      }
    });
  };

  exports.read = function(username, filename, cb) {
    var gs;
    gs = new GridStore(db, username + '/' + filename, 'r');
    return gs.open(function(err, gs) {
      return gs.read(cb);
    });
  };

  exports.remove = function(username, filename, cb) {
    var gs;
    gs = new GridStore(db, username + '/' + filename, 'r');
    console.log(username + '/' + filename);
    return gs.open(function(err, gs) {
      return gs.unlink(cb);
    });
  };

}).call(this);
