// Generated by CoffeeScript 1.4.0
(function() {
  var Folder, ObjectId, Schema, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  Folder = new Schema({
    name: String,
    parent: {
      type: ObjectId,
      ref: 'folder'
    }
  });

  Folder.index({
    name: 1,
    parent: 1
  });

  exports.Model = mongoose.model('folder', Folder);

  exports.Schema = Folder;

}).call(this);
