// Generated by CoffeeScript 1.4.0
(function() {
  var ObjectId, Schema, User, mongoose;

  mongoose = require('mongoose');

  Schema = mongoose.Schema;

  ObjectId = Schema.ObjectId;

  User = new Schema({
    username: {
      type: String,
      unique: true,
      required: true
    },
    password: String,
    uvid: {
      type: String,
      unique: true
    },
    files: [String]
  });

  User.methods.validPassword = function(password, done) {
    if (this.password === password) {
      return done(null, this);
    } else {
      return done(null, false, {
        message: 'Invalid Password'
      });
    }
  };

  exports.Model = mongoose.model('user', User);

  exports.Schema = User;

}).call(this);
